name: Deploy to EC

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
      with:
       target: /var/www/html/laravel-9-docker-crud-generation
     

    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts

     
    - name: Deploy to EC2
     # working-directory: ./var/www/html/laravel-9-docker-crud-generation
     
      run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_PUBLIC_IP }} 
          git pull origin main
          pwd
         
     

     
        

    - name: Clear SSH key
      run: rm ~/.ssh/id_rsa
