name: Deploy to EC

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts

  

    - name: Deploy to EC2
      run: |
          ssh -o StrictHostKeyChecking=no -i <(echo "$SSH_PRIVATE_KEY") ubuntur@${{ secrets.EC2_PUBLIC_IP }}
          cd /var/www/html/project_dir
          git pull origin main
          php artisan migrate --force
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
        

    - name: Clear SSH key
      run: rm ~/.ssh/id_rsa