name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  check-application:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} ' cd /var/www/html/laravel-9-docker-crud-generation && pwd && git pull origin main'
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} ' cd /var/www/html/laravel-9-docker-crud-generation/src &&  sudo composer install --no-interaction --prefer-dist --optimize-autoloader'
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} ' cd /var/www/html/laravel-9-docker-crud-generation/src && php artisan migrate --force'
       
